* JavaZone 2018 lightning talk - The Beauty and Elegance of testing in Kotlin

This file will be a work in progress helper document for my JavaZone presentation. 


** Webslides
This presentation is powered by WebSlides, which is a cool feature rich, easy-to-use presentation framework. I have downloaded Webslides as mentioned on their github page, but I have overridden and edited some settings (as you probably will when using it). Thanks to the creator of it for creating such a fantastic presentation framework :) . The license for Webslides is included below:
#+BEGIN_SRC fundamental
  MIT License

  Copyright (c) 2017 José Luis Antúnez

  Permission is hereby granted, free of charge, to any person obtaining a copy
  of this software and associated documentation files (the "Software"), to deal
  in the Software without restriction, including without limitation the rights
  to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
  copies of the Software, and to permit persons to whom the Software is
  furnished to do so, subject to the following conditions:

  The above copyright notice and this permission notice shall be included in all
  copies or substantial portions of the Software.

  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
  IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
  FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
  AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
  LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
  OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
  SOFTWARE.
   
#+END_SRC
 
My changes to Webslides code can be used by any if you want to. The content of the presentation is mine, but you may use it if you feel it is useful. If you use bigger portions, then I would be happy if you linked to this github repo. 

** Image acknowledgments 
All the images used are either public domain or logo for a programming language (take a guess). The creators and sources of the images are given below. I have downloaded all of them into this project only to be able to present without internet (because internet connections can be shaky). I do NOT present myself as the creator of these images. 

Intro image (desktop) by Jess Watters:
https://unsplash.com/photos/zljcr_RjWPA

Ferris wheel (first builder slide) by Adam Birkett:
https://unsplash.com/photos/lkNa1eg2d18

Leaf in glass of water by Sarah Dorweiler:
https://unsplash.com/photos/2s9aHF4eCjI

Book shelf photo by Paul Hanaoka:
https://unsplash.com/photos/ckQ1y8UO9ZU

Chair with balloon outro image taken by Florian Klauer:
https://unsplash.com/photos/nptLmg6jqDo
